export const Button = ({ children, variant = "primary", className = "", ...props }) => {
  const styles = { primary: "bg-emerald-700 text-white hover:bg-emerald-800", secondary: "bg-white text-gray-700 border border-gray-300 hover:bg-gray-50", warning: "bg-yellow-500 text-emerald-950", danger: "bg-red-600 text-white", ghost: "text-gray-600 hover:bg-gray-100", soft: "bg-emerald-50 text-emerald-800" };
  return <button className={`inline-flex items-center justify-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold transition ${styles[variant] || styles.primary} ${className}`} {...props}>{children}</button>;
};

export const Badge = ({ children, tone = "gray" }) => {
  const tones = { green: "bg-emerald-100 text-emerald-800", yellow: "bg-yellow-100 text-yellow-800", red: "bg-red-100 text-red-800", blue: "bg-blue-100 text-blue-800", gray: "bg-gray-100 text-gray-700", purple: "bg-purple-100 text-purple-800" };
  return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${tones[tone] || tones.gray}`}>{children}</span>;
};

export const Modal = ({ open, title, children, onClose, wide = false }) => !open ? null : <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/40 p-4"><div className={`w-full ${wide ? "max-w-5xl" : "max-w-2xl"} max-h-[92vh] overflow-auto rounded-2xl bg-white shadow-2xl`}><div className="sticky top-0 flex items-center justify-between border-b bg-white px-6 py-4"><h3 className="text-lg font-bold">{title}</h3><button onClick={onClose} className="rounded-lg px-3 py-1 text-xl hover:bg-gray-100" aria-label="Fermer">×</button></div><div className="p-6">{children}</div></div></div>;

export const Input = ({ label, ...props }) => <label className="block text-sm">{label && <span className="mb-1.5 block font-semibold text-gray-700">{label}</span>}<input {...props} className={`w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100 ${props.className || ""}`} /></label>;
export const Select = ({ label, options = [], ...props }) => <label className="block text-sm">{label && <span className="mb-1.5 block font-semibold text-gray-700">{label}</span>}<select {...props} className={`w-full rounded-lg border border-gray-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-500 ${props.className || ""}`}>{options.map(o => typeof o === "string" ? <option key={o} value={o}>{o}</option> : <option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;
export const Textarea = ({ label, ...props }) => <label className="block text-sm">{label && <span className="mb-1.5 block font-semibold text-gray-700">{label}</span>}<textarea {...props} className={`w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm outline-none focus:border-emerald-500 ${props.className || ""}`} /></label>;
export const MultiSelect = ({ label, options = [], value = [], onChange }) => <label className="block text-sm">{label && <span className="mb-1.5 block font-semibold text-gray-700">{label}</span>}<div className="max-h-40 space-y-1 overflow-auto rounded-lg border border-gray-300 p-2">{options.map(o => <label key={o.value} className="flex items-center gap-2"><input type="checkbox" checked={value.includes(o.value)} onChange={() => onChange(value.includes(o.value) ? value.filter(v => v !== o.value) : [...value, o.value])} /><span>{o.label}</span></label>)}</div></label>;
export const EmptyState = ({ title = "Aucun élément", text = "Aucune donnée ne correspond à votre recherche." }) => <div className="rounded-xl border border-dashed border-gray-300 bg-gray-50 p-10 text-center"><h3 className="font-bold">{title}</h3><p className="mt-1 text-sm text-gray-500">{text}</p></div>;
export const PageHeader = ({ title, description, action }) => <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-extrabold sm:text-3xl">{title}</h1>{description && <p className="mt-1 text-sm text-gray-500">{description}</p>}</div>{action}</div>;
export const SearchBar = ({ value, onChange, placeholder = "Rechercher..." }) => <input value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-lg border border-gray-300 bg-white px-3 py-2.5 text-sm focus:border-emerald-500 focus:outline-none" />;
export const Table = ({ headers, children }) => <div className="overflow-x-auto rounded-2xl border border-gray-200 bg-white shadow-sm"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b bg-gray-50 text-xs uppercase tracking-wide text-gray-500"><tr>{headers.map(h => <th key={h} className="px-5 py-3.5">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{children}</tbody></table></div>;
export const RowActions = ({ onView, onEdit, onDelete, onArchive }) => <div className="flex justify-end gap-1">{onView && <button title="Voir" onClick={onView} className="rounded p-2 hover:bg-gray-100">Voir</button>}{onEdit && <button title="Modifier" onClick={onEdit} className="rounded p-2 hover:bg-gray-100">Modifier</button>}{onArchive && <button title="Archiver" onClick={onArchive} className="rounded p-2 hover:bg-gray-100">Archiver</button>}{onDelete && <button title="Supprimer" onClick={onDelete} className="rounded p-2 text-red-600 hover:bg-red-50">Supprimer</button>}</div>;
export const statusTone = (status = "") => { const s = status.toLowerCase(); if (s.includes("vérifi") || s.includes("publi")) return "green"; if (s.includes("attente") || s.includes("cours") || s.includes("déclar")) return "yellow"; if (s.includes("expir") || s.includes("rejet")) return "red"; return s.includes("archiv") ? "gray" : "blue"; };
